# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enp3s0:
        dhcp4: yes
  bridges:
    br0:
        dhcp4: yes
        interfaces:
            - enp3s0
